version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    restart: always
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --mem-queue-size=0 --broadcast-address=192.168.1.12 --lookupd-tcp-address=nsqlookupd:4160 --data-path=/data
    restart: always
    volumes:
      - ~/docker-volumes/nsq/data:/data
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    restart: always
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"